### PR TITLE
Raise error when no block is passed

### LINKED ISSUE #6: Better error handling
Currently, we don't have any error handling. If we call `#emit` with no `event` symbol, nothing happens. The same happens for other methods, like `#on`, `#off`, etc.
We need to validate those params, and warn the user when something unexpected is passed.

### PR DESCRIPTION
**Pull request by rscardinho**
Raising an `ArgumentError` when no block is passed for certain methods. Fixes #6

### CODE REVIEW

File: lib/emittr/events.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ def self.included(klass)
 
     module InstanceMethods
       def on(event, &block)
-        raise ArgumentError, 'required block not passed' unless block_given?
+        no_block_error unless block_given?
```
Comment (talyssonoc) [inline lib/emittr/events.rb]: What do you think about changing this method name to `raise_no_block_error`?
